p4i integration Integrate change 68621 from 3.0 to main. Description for change 68621:
: Change 68621 by marius@marius-douglas on 2002/07/19 12:18:02
: 
: 	Compile on .NET
: 	
: 	Strange error: 
: 	   "error C2487: ____ : member of dll interface class
: 	    may not be declared with dll interface", 
: 	where ____ was replaced with 'pntr_hei', 'pntr_ldg' and 'pntr_dsc'.
: 
: Affected files ...
: 
: ... //depot/qt/3.0/src/kernel/qrichtext_p.h#59 edit

[git-p4: depot-paths = "//depot/qt/main/": change = 68622]